resources:
  - name: emailRepo
    type: GitRepo
    configuration:
      path: Manojtuguru/pipelines-project-examples
      gitProvider: github
      sha: master

pipelines:
  - name: pipe1
    steps:
      - name: test_step_1
        type: Bash
        configuration:
          integrations:
            - smtp       # replace with friendly name of your SMTP Credentials integration
        execution:
          onSuccess:
            - send_notification notifySMTP --recipients "manojtuguru@gmail.com" --subject "Build Succeeded" --body "built docker image 112.32.101.173:8081/docker-local/demo:$PIPELINE_NAME.$RUN_NUMBER"
          onComplete:
            - # can use send_notification command here
