resources:
  - name: emailRepo
    type: GitRepo
    configuration:
      path: Manojtuguru/pipelines-project-examples
      gitProvider: github
      sha: master

pipelines:
  - name: email_notifications
    steps:
      - name: email_onStart
        type: bash
        requires:
          integrations:
            - smtp
        execution:
          onStart:
            - echo "starting"
            - send_notification smtp --recipients "manojtuguru@gmail.com"
          onExecute:
            - echo "executing"

      - name: email_onExecute
        type: bash
        requires:
          integrations:
            - smtp
        triggeredBy:
          steps:
            - email_onStart
        execution:
          onExecute:
            - echo "hello world"
            - send_notification smtp --recipients "manojtuguru@gmail.com"

      - name: email_onSuccess
        type: bash
        triggeredBy:
          steps:
            - email_onExecute
        requires:
          integrations:
            - smtp
        execution:
          onStart:
            - echo "starting"
          onExecute:
            - echo "executing"
          onSuccess:
            - echo "successful"
            - send_notification smtp --recipients "manojtuguru@gmail.com"
          onFailure:
            - echo "failure"
          onComplete:
            - echo "complete"

      - name: email_onFailure
        type: bash
        triggeredBy:
          steps:
            - email_onExecute
          resources:
            - emailRepo
        requires:
          integrations:
            - smtp
        execution:
          onStart:
            - echo "starting"
          onExecute:
            - echo "executing"
            - pushd $res_emailRepo_resourcePath
            - ./executeStuff.sh
            - popd
          onSuccess:
            - echo "successful"
          onFailure:
            - echo "failure"
            - sleep 5
            - echo "hello world" > hw.txt
            - echo "goodbye cruel world" > gw.txt
            - send_notification trriplejay_smtp --body "This was sent from the ON FAILURE ssection" --show-failing-commands --recipients "manojtuguru@gmail.com" --subject "$STEP_ID did bad" --attachments "$STEP_JSON_PATH" "$STEPLET_SCRIPT_PATH" "hw.txt" "gw.txt" --attach-logs
          onComplete:
            - echo "complete"

      - name: email_onComplete_success
        type: bash
        triggeredBy:
          steps:
            - email_onSuccess
        requires:
          integrations:
            - smtp
        execution:
          onStart:
            - echo "starting"
          onExecute:
            - echo "executing"
          onSuccess:
            - echo "successful"
          onFailure:
            - echo "failure"
          onComplete:
            - echo "complete"
            - send_notification smtp --recipients "manojtuguru@gmail.com"

      - name: email_onComplete_failure
        type: bash
        triggeredBy:
          steps:
            - email_onSuccess
        requires:
          integrations:
            - smtp
        execution:
          onStart:
            - echo "starting"
          onExecute:
            - echo "executing"
            - cat badfile
          onSuccess:
            - echo "successful"
          onFailure:
            - echo "failure"
          onComplete:
            - echo "complete"
            - send_notification smtp --recipients "manojtuguru@gmail.com"

      - name: email_onComplete_badOnSuccess
        type: bash
        triggeredBy:
          steps:
            - email_onSuccess
        requires:
          integrations:
            - smtp
        execution:
          onStart:
            - echo "starting"
          onExecute:
            - echo "executing"
          onSuccess:
            - echo "successful?"
            - cat badfile
          onFailure:
            - echo "failure"
          onComplete:
            - echo "complete"
            - send_notification smtp --recipients "manojtuguru@gmail.com"

      - name: email_attachments
        type: bash
        triggeredBy:
          steps:
            - email_onStart
        requires:
          integrations:
            - smtp
        execution:
          onExecute:
            - send_notification smtp --attach-logs --recipients "manojtuguru@gmail.com" 
            - send_notification smtp --recipients "manojtuguru@gmail.com" --attach-logs

      - name: email_quick
        type: bash
        triggeredBy:
          steps:
            - email_onStart
        requires:
          integrations:
            - smtp
        execution:
          onExecute:
            - printenv
