resources:
  - name: emailRepo
    type: GitRepo
    configuration:
      path: Manojtuguru/pipelines-project-examples
      gitProvider: github
      sha: master

pipelines:
  - name: email_notifications
    steps:
      - name: email_onStart
        type: Bash
        execution:
          onStart:
            - echo "starting"
            - send_notification smtp --recipients "manojtuguru@gmail.com"
          onExecute:
            - echo "executing"
