resources:
  - name: SH script
  - type: GitRepo
  configuration:
    gitprovider: github
    path: manojtuguru/pipelines-project-examples


pipelines:
  - name : Artifactory upgrade
    steps:
      - name : Check Art Running
      type : Bash
      onStart:
        - echo "Check if the instance is running"
        - curl http://35.231.3.112:8081/artifacatory/api/system/ping
        
