resources:
  - name: SHscript
  - type: GitRepo
    configuration:
      gitprovider: github
      path: manojtuguru/pipelines-project-examples
      name: gitrepo


pipelines:
  - name : Artifactoryupgrade
    steps:
      - name : CheckArtRunning
        type : Bash
        onStart:
          - echo "Check if the instance is running"
          - curl http://35.231.3.112:8081/artifacatory/api/system/ping
