resources:
  - name: project_example
    type: GitRepo
    configuration:
      gitProvider:  github
      path: manojtuguru/project-examples

pipelines:
  - name : Artifactoryupgrade
    steps:
      - name : CheckArtRunning
        type : Bash
        execution:
         onExecute:
          - echo "Check if the instance is running"
          - curl http://10.142.15.228:8081/artifacatory/api/system/ping
         onSuccess:
          - done "success" 
